import { WebSocketProvider } from '@/contexts/WebSocketContext';
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from '../components/Header';
import "./globals.css";

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-inter',
// })
const ibmPlexMono = localFont({
  src: [
    {
      path: '../public/fonts/IBMPlexMono-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/IBMPlexMono-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/IBMPlexMono-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/IBMPlexMono-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-ibm-plex-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ibmPlexMono.variable} px-[88px] bg-custom-darkest`}>
        <div className="min-h-screen bg-custom-darkest ">
          <Header />
          <WebSocketProvider>
            {children}
          </WebSocketProvider>
        </div>
      </body>
    </html>
  );
}
